config       : ./config.yaml
dataset      : CiteSeer
data_path    : ./data
device       : cuda
imb_ratio    : 100
net          : GATV2
feat_dim     : 256
early_stop   : True
n_head       : 8
loss_type    : ce
ife          : True
seed         : 100
dis          : 1
if_lr        : 0.001
env_lr       : 0.01
weight_decay : 0.0005
epochs       : 2000
lr_min       : 1e-06
DMA_T        : 2
repetitions  : 5
alpha        : 0.5
dropout      : 0.5
pred_temp    : 2
warmup       : 1
verbose      : False
verbose_path : ./runs
write        : False
